# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  elalang_config = debug
endif
ifeq ($(config),release)
  elalang_config = release
endif
ifeq ($(config),lexer)
  elalang_config = lexer
endif

PROJECTS := elalang

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

elalang:
ifneq (,$(elalang_config))
	@echo "==== Building elalang ($(elalang_config)) ===="
	@${MAKE} --no-print-directory -C . -f elalang.make config=$(elalang_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f elalang.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  lexer"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   elalang"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"