name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:  
    

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install llvm
      run: sudo apt install llvm-dev llvm-runtime llvm
    - name: Install headers
      run: sudo curl -L https://raw.githubusercontent.com/muellan/clipp/master/include/clipp.h -o /usr/include/clipp.h
    - name: make
      run: make
